#!/usr/bin/env python3
"""Generate one real ARDY baseline through a public third-party ZeroGPU host.

The inference host is NOT an NVIDIA-operated Space. It is used only to exercise
official NVIDIA ARDY checkpoint output without paying for GPU compute.
"""

from __future__ import annotations

import argparse
import json
import shutil
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any

from gradio_client import Client


def _source_path(value: Any) -> str:
    if isinstance(value, str):
        return value
    if isinstance(value, dict):
        for key in ("path", "url", "name"):
            candidate = value.get(key)
            if isinstance(candidate, str) and candidate:
                return candidate
    path = getattr(value, "path", None)
    if isinstance(path, str):
        return path
    raise TypeError(f"Unsupported Gradio file result: {type(value)!r} {value!r}")


def _copy_result(client: Client, value: Any, dest: Path) -> None:
    src = _source_path(value)
    dest.parent.mkdir(parents=True, exist_ok=True)
    if src.startswith(("http://", "https://")):
        urllib.request.urlretrieve(src, dest)
        return

    source = Path(src)
    if source.exists():
        shutil.copy2(source, dest)
        return

    # gr.api() endpoints can return a server-local temp path as a plain string
    # instead of a gr.File value. Gradio still serves temp outputs through its
    # file route, so recover the generated bytes from the same Space.
    encoded = urllib.parse.quote(src, safe="/")
    base = str(client.src).rstrip("/")
    candidates = [
        f"{base}/gradio_api/file={encoded}",
        f"{base}/file={encoded}",
    ]
    errors = []
    for url in candidates:
        try:
            urllib.request.urlretrieve(url, dest)
            if dest.exists() and dest.stat().st_size > 0:
                return
        except Exception as exc:
            errors.append(f"{url}: {exc}")
            if dest.exists():
                dest.unlink()

    raise FileNotFoundError(
        f"Could not recover Gradio server temp file {src!r}; " + " | ".join(errors)
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--space", default="VIDraft/CozyClay")
    ap.add_argument("--prompt", default="A person accelerates smoothly from a run into a full sprint.")
    ap.add_argument("--duration", type=float, default=4.0)
    ap.add_argument("--diffusion-steps", type=int, default=4)
    ap.add_argument("--cfg-weight", type=float, default=2.0)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--output-dir", type=Path, required=True)
    args = ap.parse_args()

    args.output_dir.mkdir(parents=True, exist_ok=True)
    client = Client(args.space, verbose=False)

    try:
        api = client.view_api(print_info=False, return_format="dict")
    except TypeError:
        api = {"note": "installed gradio_client did not support structured view_api"}
    (args.output_dir / "space-api.json").write_text(
        json.dumps(api, indent=2, default=str) + "\n",
        encoding="utf-8",
    )

    request_json = json.dumps(
        {
            "prompt": args.prompt,
            "duration": args.duration,
            "seed": args.seed,
        }
    )
    result = client.predict(request_json, api_name="/generate_motion")
    if not isinstance(result, (list, tuple)) or len(result) < 2:
        raise RuntimeError(f"Unexpected /generate_motion result: {result!r}")

    print("raw generate_motion result:", repr(result))
    npz, report = result[:2]
    _copy_result(client, npz, args.output_dir / "motion.npz")
    if not isinstance(report, dict):
        report = {"raw_report": report}
    (args.output_dir / "metadata.json").write_text(
        json.dumps(report, indent=2, default=str) + "\n",
        encoding="utf-8",
    )

    request = {
        "space": args.space,
        "host_classification": "third_party_zero_gpu",
        "authoritative_model_source": "nvidia/ARDY-Core-RP-20FPS-Horizon40",
        "prompt": args.prompt,
        "duration_requested_s": args.duration,
        "seed_requested": args.seed,
        "api_name": "/generate_motion",
        "host_note": "CozyClay replaces the gated Llama base with a public mirror while retaining the official ARDY Core checkpoint; compatibility evidence only.",
    }
    (args.output_dir / "request.json").write_text(
        json.dumps(request, indent=2) + "\n",
        encoding="utf-8",
    )
    print(json.dumps(request, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
